# Generated by Django 5.0.3 on 2024-03-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avaliacao",
            old_name="atualizacao",
            new_name="atualizado_em",
        ),
        migrations.RenameField(
            model_name="avaliacao",
            old_name="criacao",
            new_name="criacao_em",
        ),
        migrations.RenameField(
            model_name="curso",
            old_name="atualizacao",
            new_name="atualizado_em",
        ),
        migrations.RenameField(
            model_name="curso",
            old_name="criacao",
            new_name="criacao_em",
        ),
    ]
