# Generated by Django 5.0.3 on 2024-03-19 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_rename_atualizacao_avaliacao_atualizado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
